<a href="https://colab.research.google.com/github/Srii-983/PyTorch_fundamentals1/blob/main/day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import pandas as ps
import numpy as np
import matplotlib.pyplot as plt

In [13]:
#manipulating tensor(tensor operations- addition,subtraction,division,multiplication,matrix multiplication)
tensor=torch.tensor([1,2,3])
tensor+100

tensor([101, 102, 103])

In [14]:
#multiply tensor by 10
tensor=tensor*10
tensor

tensor([10, 20, 30])

In [15]:
#subtract 10
tensor=tensor-10
tensor

tensor([ 0, 10, 20])

In [16]:
#trying out pyTorch in-built function
torch.mul(tensor,10)


tensor([  0, 100, 200])

In [18]:
torch.add(tensor,10)

tensor([10, 20, 30])

In [20]:
#matrix multiplication
#1st way element-wise multiplication
print(tensor,"*",tensor)
print(f"equals:{tensor*tensor}")

tensor([ 0, 10, 20]) * tensor([ 0, 10, 20])
equals:tensor([  0, 100, 400])


In [21]:
torch.matmul(tensor,tensor)

tensor(500)

In [22]:
tensor

tensor([ 0, 10, 20])

In [33]:
#matrix multiplication by dot product
tensor_A = torch.tensor([7])
tensor_B = torch.tensor([25])
tensor_A.shape, tensor_B.shape


(torch.Size([1]), torch.Size([1]))

In [34]:
torch.matmul(tensor_A,tensor_B)

tensor(175)

In [39]:
tenA=torch.tensor([8,3,6])
tenA.shape

torch.Size([3])

In [41]:
##finding min,max,mean,sum,etc(tensor aggregation)
x=torch.arange(1,100,20)
x

tensor([ 1, 21, 41, 61, 81])

In [42]:
torch.max(x)

tensor(81)

In [44]:
torch.min(x)

tensor(1)

In [46]:
#mean require float32 to work
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(41.), tensor(41.))

In [47]:
torch.sum(x),x.sum()

(tensor(205), tensor(205))