<a href="https://colab.research.google.com/github/Srii-983/PyTorch_fundamentals1/blob/main/day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as ps
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#reshaping,stacking,squeezing tensors
x=torch.arange(1.,5)
x,x.shape


(tensor([1., 2., 3., 4.]), torch.Size([4]))

In [ ]:
#add an extra dimension
x_reshaped=x.reshape(4,)
x_reshaped,x_reshaped.shape

(tensor([1., 2., 3., 4.]), torch.Size([4]))

In [ ]:
#change the view
z=x.view(1,4)
z,z.shape


(tensor([[1., 2., 3., 4.]]), torch.Size([1, 4]))

In [ ]:
#changing z changes x
z[:,0]=4
z,x

(tensor([[4., 2., 3., 4.]]), tensor([4., 2., 3., 4.]))

In [ ]:
#stack tensors on top of each  other
x_stacked=torch.stack([x,x,x,x],dim=1) #dim=0,3
x_stacked

tensor([[4., 4., 4., 4.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.]])

In [ ]:
#torch.squeeze=removes all single dimensions from a target tensor
x_reshaped,x_reshaped.shape

(tensor([4., 2., 3., 4.]), torch.Size([4]))

In [ ]:
x_squeezed=x_reshaped.squeeze()
x_squeezed,x_squeezed.shape

(tensor([4., 2., 3., 4.]), torch.Size([4]))

In [ ]:
#torch.unsqueeze
x_unsqueezed=x_squeezed.unsqueeze(dim=0)
x_unsqueezed,x_unsqueezed.shape

(tensor([[4., 2., 3., 4.]]), torch.Size([1, 4]))

In [ ]:
#torch.permute-rearrange dimensions of  atarget tensor in a specified order
x_ori=torch.rand(size=(224,224,3))
#permute the original tensors to arrange the axis or dim order
x_permuted=x_ori.permute(2,0,1)#shifts axis 0->1,1->2,2->0
x_ori.shape, x_permuted.shape


(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [ ]:
x_ori

tensor([[[0.9367, 0.2707, 0.8304],
         [0.7994, 0.2313, 0.3682],
         [0.9767, 0.2923, 0.1208],
         ...,
         [0.1146, 0.5775, 0.5742],
         [0.3562, 0.3037, 0.6948],
         [0.6567, 0.8556, 0.6998]],

        [[0.6049, 0.3386, 0.6828],
         [0.5225, 0.8205, 0.1495],
         [0.9037, 0.7722, 0.8741],
         ...,
         [0.0287, 0.6216, 0.2776],
         [0.4952, 0.4560, 0.2673],
         [0.9756, 0.9828, 0.9600]],

        [[0.9630, 0.4087, 0.6854],
         [0.2433, 0.6506, 0.3958],
         [0.5921, 0.8192, 0.1133],
         ...,
         [0.4895, 0.0761, 0.0894],
         [0.2690, 0.0126, 0.2546],
         [0.0639, 0.6039, 0.3771]],

        ...,

        [[0.9814, 0.4925, 0.0024],
         [0.0102, 0.3619, 0.8324],
         [0.1491, 0.5478, 0.2994],
         ...,
         [0.4528, 0.7707, 0.9128],
         [0.6398, 0.0753, 0.0978],
         [0.2853, 0.2911, 0.8629]],

        [[0.1499, 0.1046, 0.2624],
         [0.6449, 0.0589, 0.1077],
         [0.

In [ ]:
x_ori[0,0,0]=728218
x_ori[0,0,0],x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

In [ ]:
#indexing with pytorch is similar to indexing with numpy
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0] #index on tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0] #index on middle bracket (dim=1)

tensor([1, 2, 3])

In [ ]:
x[0][0][0] #indexx on most inner bracket(dim=last)

tensor(1)

In [ ]:
x[0][1][1]

tensor(5)

In [ ]:
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
#get all values of 0th and 1st dimensons but only index 1 and 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
#get all values of 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [ ]:
#index on x to return 9
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
#pyRorch tensors and numpy
#numpy is a popular scientific python numeerical computing library
#data in numpy, want inn pytorch tensor -> torch,from_numpy(ndarray)
#pytorch tensor-> numpy-> torch.Tensor.numpy()

In [ ]:
a= np.arange(1.0,8.0)
tensor=torch.from_numpy(a) #when converting from numpy->pytorch ,pytorch reflects numpy as default datatype of float64 unlesss specified otherwise
a,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
a.dtype

dtype('float64')

In [ ]:
torch.arange(1.0,8.0).dtype

torch.float32