<a href="https://colab.research.google.com/github/Srii-983/PyTorch_fundamentals1/blob/main/Day4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

In [4]:
#tensor to numpy array
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [5]:
#changing tensor what happens to numpy
tensor=tensor +1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [6]:
#reproducbility(trying to take random out of random)
torch.rand(3,3)

tensor([[0.3242, 0.4588, 0.3780],
        [0.7502, 0.1387, 0.0098],
        [0.8704, 0.2887, 0.2875]])

In [7]:
Random_seed=42
torch.manual_seed(Random_seed)
random_c=torch.rand(3,4)
torch.manual_seed(Random_seed)
random_d=torch.rand(3,4)
print(random_c)
print(random_d)
print(random_c==random_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
