<a href="https://colab.research.google.com/github/Srii-983/PyTorch_fundamentals1/blob/main/Pytorch_fundamnetals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as ps
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


In [2]:
#scalar
scalar=torch.tensor(7)
scalar


tensor(7)

In [3]:
scalar.ndim #scalar is dimensionless

0

In [4]:
#get tensor back as python int
scalar.item()

7

In [5]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape #pair of lements in square bracket

torch.Size([2])

In [8]:
#matrix
matrix=torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
matrix.ndim


2

In [10]:
matrix.shape

torch.Size([2, 2])

In [11]:
#Tensor
TENSOR=torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [19]:
#creating random tensors of size (3,4) ,it has 12 (3*4) elements
random_tensor=torch.rand(3,4)
random_tensor


tensor([[0.4525, 0.9016, 0.0435, 0.7912],
        [0.4519, 0.3188, 0.9506, 0.4404],
        [0.7964, 0.9803, 0.4855, 0.0693]])

In [20]:
random_tensor.ndim #(3,4) is 2 dimension

2

In [21]:
#creating random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(224,224,3)) #height,width,colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [26]:
#zeros and ones
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
ones.dtype

torch.float32

In [29]:
random_tensor.dtype

torch.float32

In [32]:
#creating range of tensors
one_ten=torch.arange(start=0,end=37,step=5)
one_ten

tensor([ 0,  5, 10, 15, 20, 25, 30, 35])

In [33]:
#creating tensors alike
ten_zeros=torch.zeros_like(input=one_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0])

Tensor Datatypes

In [38]:
#Float 32 tensor
float_32 = torch.tensor([3.0,6.0,9.0],
                       dtype=None, #what datatype is the tensor (e.g float32 or float16)
                       device=None,
                       requires_grad=False)
float_32


tensor([3., 6., 9.])

In [39]:
float_32.dtype

torch.float32

In [40]:
#converting float_32 to float_16
float_16=float_32.type(torch.float16)
float_16

tensor([3., 6., 9.], dtype=torch.float16)

In [41]:
float_16*float_32

tensor([ 9., 36., 81.])

In [42]:
int_32=torch.tensor([3,6,4],dtype=torch.int32)
int_32

tensor([3, 6, 4], dtype=torch.int32)

In [43]:
float_32*int_32

tensor([ 9., 36., 36.])

In [46]:
#getting information from tensors(dtype,shaoe,devivce)
#create my own tensor
some_tensor=torch.rand(2,4)
some_tensor

tensor([[0.2929, 0.0219, 0.4351, 0.3138],
        [0.5495, 0.7069, 0.4491, 0.2089]])

In [47]:
#finding details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.2929, 0.0219, 0.4351, 0.3138],
        [0.5495, 0.7069, 0.4491, 0.2089]])
Datatype of tensor: torch.float32
shape of tensor: torch.Size([2, 4])
Device of tensor: cpu
